
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[451] =
    {   0,
       46,   44,   45,    1,   44,   45,    1,   45,    1,   44,
       45,   41,   44,   45,   44,   45,   41,   44,   45,   41,
       44,   45,   44,   45,   43,   44,   45,   41,   44,   45,
       41,   44,   45,   43,   44,   45,   41,   44,   45,   25,
       44,   45,   25,   44,   45,   41,   44,   45,   41,   44,
       45,   41,   44,   45,   41,   44,   45,   41,   44,   45,
       42,   44,   45,   22,   42,   44,   45,   42,   44,   45,
       42,   44,   45,   42,   44,   45,   42,   44,   45,   42,
       44,   45,   42,   44,   45,   42,   44,   45,   42,   44,
       45,   42,   44,   45,   42,   44,   45,   42,   44,   45,

       42,   44,   45,   42,   44,   45,   42,   44,   45,   42,
       44,   45,   42,   44,   45,   42,   44,   45,   41,   44,
       45,    1,   41,   39,   41,   41,   41,   25,   25,   10,
       41,   30,16419,   27,   32,   25,   25,   31,   25,   43,
       41,   41,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   14,   22,   42,   42,   42,
       42,   42,   42,   42,   42,   42,    3,   22,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       41,   39,   38,   38,   30,   30, 8227, 8227,   29, 8227,

       33, 8227,   34, 8227,   27,   28,   26,   31,   31,   31,
       32,   41,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       15,   22,   42,   42,   42,   42,   22,   42,   42,   42,
       22,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,    9,   22,
       42,    2,   42,   42,   42,   42,   42,   30,   30,   29,
       29,   29,   34,   34,   33,   34,   28,   26,   31,   42,
       42,   42,   42,   11,   22,   42,   42,   42,   42,   42,
       42,   42,    4,   22,   42,   42,   42,   42,   42,   42,

       42,   42,   42,   42,   23,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   24,
       42,   42,   42,   42,   30,   29,   29,   34,   37,   36,
       42,   42,   42,   16,   22,   42,    7,   22,   42,   42,
       42,   42,   42,   22,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       22,   42,   42,   42,   13,   22,   42,   17,   42,   29,
       37,   37,   37,   36,   37,   36,   36,   36,   42,    5,
       22,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   19,   22,   42,   42,    6,   22,   42,

       42,    8,   42,   42,   42,   40,   37,   36,   37,   36,
       37,   36,   37,   36,   42,   42,   12,   22,   42,   21,
       22,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       40,   36,   37,   18,   22,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   20,   22,   42
    } ;

static const flex_int16_t yy_accept[382] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   17,
       20,   23,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   68,   71,   74,   77,
       80,   83,   86,   89,   92,   95,   98,  101,  104,  107,
      110,  113,  116,  119,  122,  123,  124,  124,  125,  125,
      126,  126,  126,  127,  128,  128,  129,  130,  132,  132,
      133,  133,  133,  134,  135,  135,  135,  136,  136,  137,
      137,  138,  139,  140,  141,  142,  143,  144,  145,  146,
      147,  148,  149,  150,  151,  152,  153,  154,  155,  156,
      159,  160,  161,  162,  163,  164,  165,  166,  167,  170,

      171,  172,  173,  174,  175,  176,  177,  178,  179,  180,
      181,  182,  183,  184,  185,  186,  187,  188,  189,  190,
      191,  192,  193,  193,  194,  195,  196,  197,  197,  197,
      197,  198,  199,  199,  201,  203,  205,  206,  207,  207,
      207,  207,  207,  208,  208,  209,  210,  212,  213,  214,
      215,  216,  217,  218,  219,  220,  221,  222,  223,  224,
      225,  226,  227,  228,  229,  230,  231,  234,  235,  236,
      237,  239,  240,  241,  243,  244,  245,  246,  247,  248,
      249,  250,  251,  252,  253,  254,  255,  256,  257,  258,
      259,  262,  264,  265,  266,  267,  268,  268,  268,  268,

      268,  268,  268,  269,  270,  270,  270,  271,  272,  273,
      273,  274,  275,  277,  278,  278,  278,  278,  279,  280,
      281,  282,  283,  284,  287,  288,  289,  290,  291,  292,
      293,  296,  297,  298,  299,  300,  301,  302,  303,  304,
      305,  307,  308,  309,  310,  311,  312,  313,  314,  315,
      316,  317,  318,  319,  320,  322,  323,  324,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  326,  326,
      326,  326,  327,  328,  329,  330,  330,  331,  332,  333,
      334,  337,  340,  341,  342,  343,  344,  346,  347,  348,
      349,  350,  351,  352,  353,  354,  355,  356,  357,  358,

      359,  360,  361,  363,  364,  365,  368,  370,  370,  370,
      370,  370,  370,  370,  371,  371,  372,  373,  374,  376,
      376,  377,  378,  379,  380,  383,  384,  385,  386,  387,
      388,  389,  390,  391,  392,  393,  394,  397,  398,  401,
      402,  404,  405,  406,  407,  407,  407,  408,  408,  410,
      412,  414,  415,  416,  417,  420,  423,  424,  425,  426,
      427,  428,  429,  430,  431,  432,  434,  437,  438,  439,
      440,  441,  442,  443,  444,  445,  446,  447,  448,  451,
      451
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   10,   21,
       22,   23,   24,   10,   25,   26,   25,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   32,
       30,   30,   30,   30,   30,   30,   30,   33,   30,   30,
       34,   35,   36,    7,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   10,   62,   10,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    3,    1,    4,    4,    4,    4,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    5,
        5,    6,    5,    1,    1,    1,    5,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    6,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1
    } ;

static const flex_int16_t yy_base[397] =
    {   0,
        0,    0,  901,  902,  902,  902,  897,  877,   58,  876,
       57,  862,  902,   54,   55,   66,   75,   84,  130,  876,
       66,  873,   69,  902,    0,  102,   42,   54,   86,   53,
       92,   90,  843,  113,  842,  112,  114,  850,  119,   22,
       71,  846,  844,   67,  902,  902,   64,  883,  885,  902,
      878,  157,  902,  902,  164,    0,    0,  902,  872,  168,
      874,  881,  209,  174,  184,  190,  902,  241,  902,  869,
        0,  273,  902,  902,  860,  191,    0,    0,  202,  827,
      826,  828,  836,  822,  161,  838,  837,  824,  830,  816,
      817,  814,  814,  820,  817,  815,  812,  809,    0,  811,

      175,  812,  806,  802,  811,  818,   84,  818,  801,  804,
      151,  802,  807,  802,  123,  186,  798,   60,  804,  807,
      902,  902,  237,  902,  839,  902,  305,  836,  220,  843,
      902,  902,  831,  333,  902,  365,  902,  216,  257,  236,
      312,    0,  230,  277,  240,  369,  902,  822,  788,  800,
      793,  802,  797,  796,  790,  715,  705,  194,  719,  717,
      713,  705,  711,  698,  713,  712,    0,  698,  250,  693,
      705,  698,  694,    0,  690,  690,  675,  675,  680,  667,
      669,  658,  662,  664,  649,  663,  644,  645,  644,  650,
        0,    0,  649,  651,  640,  631,  301,  305,  309,  672,

      362,  340,  362,  398,  663,  658,    0,  902,  430,  383,
      366,  434,  902,  902,  449,  101,  113,  902,  464,  618,
      617,  627,  621,    0,  622,  612,  610,  618,  607,  614,
        0,  610,  616,  609,  591,  603,  591,  599,  573,  566,
        0,  583,  581,  576,  563,  552,  547,  553,  558,  544,
      555,  541,  269,  524,    0,  522,  531,  529,  425,  434,
      482,  555,  491,  553,  495,  500,  505,  496,  545,  251,
      402,  429,  502,  531,  563,  274,  595,  517,  491,  504,
        0,    0,  491,  486,  491,  491,  480,  478,  461,  460,
      459,  458,  445,  429,  439,  434,  414,  422,  400,  409,

      392,  386,  382,  384,  380,    0,    0,  417,  548,  565,
      581,  585,  416,  612,  416,  495,  632,  902,  664,  547,
      574,  668,  902,  373,    0,  361,  348,  335,  326,  319,
      331,  332,  332,  327,  322,  299,    0,  304,    0,  294,
        0,  301,  294,  902,  590,  332,  683,  616,  613,  698,
      902,  702,  282,  293,    0,    0,  283,  278,  279,  268,
      251,  247,  238,  245,  274,  717,    0,  216,  205,  213,
      204,  188,  162,  154,  156,  133,  113,   75,    0,  902,
      760,  766,  769,  772,  778,  784,  790,  794,  798,  804,
       90,  810,  816,  822,  825,  831

    } ;

static const flex_int16_t yy_def[397] =
    {   0,
      380,    1,  380,  380,  380,  380,  380,  380,  381,  380,
      380,  382,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  383,  384,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  380,  380,  380,  381,  380,  381,  380,
      380,  382,  380,  380,  380,   18,   19,  380,  380,  380,
      385,  386,  387,  380,  380,  380,  380,  380,  380,  388,
       19,  380,  380,  380,  380,  380,  383,  383,  384,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      380,  380,  389,  380,  380,  380,  380,  385,  390,  386,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  391,  388,  380,  380,  380,  380,  380,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  389,  392,  392,  389,

      393,  380,  380,  380,  394,  380,  134,  380,  380,  380,
      380,  380,  380,  380,  380,  391,  395,  380,  380,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  392,  392,
      392,  392,  396,  389,  389,  393,  393,  380,  394,  390,
      380,  380,  380,  380,  380,  395,  380,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383,  383,  392,  392,  396,
      396,  392,  393,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  380,  392,  396,  380,  380,  380,  380,
      380,  380,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  392,  380,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,    0,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380

    } ;

static const flex_int16_t yy_nxt[966] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       10,   14,   15,   16,   17,   18,   19,   19,   19,   20,
       21,   22,   23,   24,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   13,    4,   13,   26,   27,   28,   29,
       30,   31,   32,   33,   25,   34,   25,   35,   25,   36,
       25,   37,   38,   39,   40,   25,   41,   42,   25,   43,
       25,   44,   24,   48,   50,   53,  115,   54,   55,  122,
       56,   57,   57,   57,  116,   46,   46,   58,   46,   59,
       80,   60,   60,   60,   60,   61,   75,   46,   46,   62,
       46,   76,   49,  216,   89,   81,   46,   63,   49,   64,

       64,   64,   65,   90,   82,  193,   83,  194,  117,   66,
       67,   68,   67,   84,   69,  379,   70,   77,   77,   77,
       77,  118,   66,   85,   67,   68,   67,   94,  121,  177,
       86,   69,  275,   87,  178,   95,   88,   96,   79,   91,
       97,   92,   70,   63,  277,   71,   71,   71,   71,  103,
       93,  106,  275,  104,  378,   99,   67,   72,   67,  380,
       73,  100,  101,  110,  277,  125,  107,  105,  187,  108,
       67,   72,   67,  111,  112,  188,  113,   73,  114,   60,
       60,   60,   60,   60,   60,   60,   60,   63,  182,   64,
       64,   64,   65,  377,  126,  127,  126,   63,  174,   65,

       65,   65,   65,  183,  137,  138,  138,  174,  126,  127,
      126,  132,   46,  148,  154,  155,  174,   77,   77,   77,
       77,  137,  133,  189,  134,  134,  134,  134,  170,  171,
      129,  138,  138,  376,   45,  135,  136,  135,   79,  198,
      199,  190,  200,  217,  174,  191,  214,  227,  228,  135,
      136,  135,  139,  139,  174,  375,  140,  141,  141,  141,
      218,  270,   67,  214,   67,   45,  147,   67,  147,   67,
      374,  201,  140,  141,  141,  141,   67,  218,   67,  344,
      147,   67,  147,   67,  144,  144,  174,  373,  145,  146,
      146,  146,  145,  146,  146,  146,  372,  236,  199,  147,

      237,  147,  174,  198,  199,  319,  200,  260,  261,  371,
      262,  260,  261,  147,  262,  147,  202,  202,  370,  369,
      203,  204,  204,  204,  302,  319,  303,  215,  215,  215,
      215,  126,  368,  126,  367,  201,  174,  365,   67,  263,
       67,  364,  363,  263,  362,  126,  361,  126,  207,  207,
      207,  207,   67,  360,   67,  203,  204,  204,  204,  208,
      209,  208,  199,  174,  198,  198,  261,  266,  174,  359,
      261,  358,  357,  208,  209,  208,  210,  210,  356,  174,
      211,  212,  212,  212,  219,  219,  219,  219,  126,  355,
      126,  213,  213,  213,  213,  147,  267,  147,  211,  212,

      212,  212,  126,  354,  126,  213,  213,  213,  213,  147,
      174,  147,  353,  268,  268,  268,  268,  272,  273,  273,
      273,  264,  344,  198,  126,  343,  126,  260,  261,  342,
      262,  316,  317,  317,  317,  174,  260,  261,  126,  262,
      126,  271,  271,  341,  340,  272,  273,  273,  273,  274,
      274,  274,  274,  339,  338,  208,  208,  208,  208,  263,
      213,  174,  213,  337,  215,  215,  215,  215,  263,  208,
      208,  208,  208,  174,  213,   67,  213,   67,  336,  219,
      219,  219,  219,  335,  260,  261,  261,  262,  334,   67,
      147,   67,  147,  260,  260,  261,  310,  198,  199,  174,

      200,  333,  312,  198,  147,  313,  147,  198,  198,  332,
      266,  268,  268,  268,  268,  174,  263,  314,  314,  314,
      314,  318,  126,  318,  126,  311,  331,  330,  208,  201,
      208,  329,  174,  328,  267,  318,  126,  318,  126,  267,
      327,  326,  208,  261,  208,  325,  274,  274,  274,  274,
      260,  261,  260,  262,  324,  270,  199,  213,  380,  213,
      308,  198,  321,  322,  322,  322,  198,  345,  260,  307,
      346,  213,  306,  213,  315,  315,  305,  304,  316,  317,
      317,  317,  263,  260,  260,  301,  310,  260,  261,  318,
      262,  318,  260,  261,  300,  262,  174,  299,  298,  311,

      323,  174,  323,  318,  297,  318,  320,  320,  296,  261,
      321,  322,  322,  322,  323,  311,  323,  295,  294,  263,
      293,  323,  292,  323,  263,  291,  260,  314,  314,  314,
      314,  349,  350,  350,  350,  323,  290,  323,  208,  351,
      208,  351,  260,  289,  288,  174,  261,  347,  347,  347,
      347,  261,  208,  351,  208,  351,  287,  255,  318,  286,
      318,  285,  284,  283,  174,  174,  282,  281,  280,  279,
      278,  131,  318,  270,  318,  348,  348,  264,  258,  349,
      350,  350,  350,  352,  352,  352,  352,  257,  256,  174,
      351,  255,  351,  254,  323,  253,  323,  174,  347,  347,

      347,  347,  252,  251,  351,  250,  351,  249,  323,  318,
      323,  318,  248,  366,  366,  366,  366,  352,  352,  352,
      352,  247,  246,  318,  351,  318,  351,  245,  323,  244,
      323,  243,  366,  366,  366,  366,  242,  241,  351,  240,
      351,  174,  323,  351,  323,  351,  239,  238,  174,  235,
      234,  233,  232,  174,  231,  230,  229,  351,  226,  351,
       47,   47,   47,   47,   47,   47,   51,  174,   51,   51,
       51,   51,   77,   77,   77,   78,   78,   78,  128,  128,
      128,  128,  128,  128,  130,  130,  130,  130,  130,  130,
      131,  131,  131,  131,  131,  131,  143,  143,  197,  197,

      197,  197,  197,  197,  205,  205,  205,  205,  205,  205,
      259,  259,  259,  259,  259,  259,  265,  265,  265,  265,
      265,  265,  269,  269,  269,  269,  269,  269,  276,  225,
      276,  309,  309,  309,  309,  309,  309,  224,  174,  223,
      222,  221,  220,   46,  206,   45,  129,  124,  196,  195,
      192,  186,  185,  184,  181,  180,  179,  176,  175,  174,
      173,  172,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  153,  152,  151,  150,
      149,   46,  142,   45,  129,   74,  124,  380,  123,  120,
      119,  109,  102,   98,   46,   74,   52,   46,   46,   45,

      380,    3,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380
    } ;

static const flex_int16_t yy_chk[966] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    9,   11,   14,   40,   15,   15,   47,
       15,   15,   15,   15,   40,   14,   15,   15,   11,   16,
       27,   16,   16,   16,   16,   17,   21,   21,   44,   17,
       23,   23,    9,  391,   30,   27,   17,   18,   47,   18,

       18,   18,   18,   30,   28,  118,   28,  118,   41,   18,
       18,   18,   18,   28,   18,  378,   18,   26,   26,   26,
       26,   41,   18,   29,   18,   18,   18,   32,   44,  107,
       29,   18,  216,   29,  107,   32,   29,   32,   26,   31,
       32,   31,   18,   19,  217,   19,   19,   19,   19,   36,
       31,   37,  216,   36,  377,   34,   19,   19,   19,   52,
       19,   34,   34,   39,  217,   52,   37,   36,  115,   37,
       19,   19,   19,   39,   39,  115,   39,   19,   39,   55,
       55,   55,   55,   60,   60,   60,   60,   64,  111,   64,
       64,   64,   64,  376,   60,   60,   60,   65,  375,   65,

       65,   65,   65,  111,   64,   66,   66,  374,   60,   60,
       60,   63,   76,   76,   85,   85,  373,   79,   79,   79,
       79,   64,   63,  116,   63,   63,   63,   63,  101,  101,
      129,  138,  138,  372,  129,   63,   63,   63,   79,  123,
      123,  116,  123,  143,  371,  116,  138,  158,  158,   63,
       63,   63,   68,   68,  370,  369,   68,   68,   68,   68,
      143,  270,  140,  138,  140,  270,  145,   68,  145,   68,
      368,  123,  139,  139,  139,  139,  140,  143,  140,  365,
      145,   68,  145,   68,   72,   72,  364,  363,   72,   72,
       72,   72,  144,  144,  144,  144,  362,  169,  123,   72,

      169,   72,  361,  197,  197,  276,  197,  198,  198,  360,
      198,  199,  199,   72,  199,   72,  127,  127,  359,  358,
      127,  127,  127,  127,  253,  276,  253,  141,  141,  141,
      141,  127,  357,  127,  354,  197,  353,  346,  141,  198,
      141,  343,  342,  199,  340,  127,  338,  127,  134,  134,
      134,  134,  141,  336,  141,  202,  202,  202,  202,  134,
      134,  134,  197,  335,  201,  201,  198,  201,  334,  333,
      199,  332,  331,  134,  134,  134,  136,  136,  330,  329,
      136,  136,  136,  136,  146,  146,  146,  146,  203,  328,
      203,  136,  211,  136,  211,  146,  201,  146,  210,  210,

      210,  210,  203,  327,  203,  136,  211,  136,  211,  146,
      326,  146,  324,  204,  204,  204,  204,  271,  271,  271,
      271,  313,  308,  201,  204,  305,  204,  259,  259,  304,
      259,  315,  315,  315,  315,  303,  260,  260,  204,  260,
      204,  209,  209,  302,  301,  209,  209,  209,  209,  212,
      212,  212,  212,  300,  299,  272,  209,  272,  209,  259,
      212,  298,  212,  297,  215,  215,  215,  215,  260,  272,
      209,  272,  209,  296,  212,  215,  212,  215,  295,  219,
      219,  219,  219,  294,  261,  261,  259,  261,  293,  215,
      219,  215,  219,  263,  263,  260,  263,  265,  265,  292,

      265,  291,  266,  266,  219,  266,  219,  267,  267,  290,
      267,  268,  268,  268,  268,  289,  261,  273,  273,  273,
      273,  316,  268,  316,  268,  263,  288,  287,  273,  265,
      273,  286,  285,  284,  266,  316,  268,  316,  268,  267,
      283,  280,  273,  261,  273,  279,  274,  274,  274,  274,
      309,  309,  263,  309,  278,  269,  265,  274,  264,  274,
      262,  266,  320,  320,  320,  320,  267,  310,  310,  258,
      310,  274,  257,  274,  275,  275,  256,  254,  275,  275,
      275,  275,  309,  311,  311,  252,  311,  312,  312,  275,
      312,  275,  345,  345,  251,  345,  250,  249,  248,  310,

      321,  247,  321,  275,  246,  275,  277,  277,  245,  309,
      277,  277,  277,  277,  321,  311,  321,  244,  243,  312,
      242,  277,  240,  277,  345,  239,  310,  314,  314,  314,
      314,  348,  348,  348,  348,  277,  238,  277,  314,  349,
      314,  349,  311,  237,  236,  235,  312,  317,  317,  317,
      317,  345,  314,  349,  314,  349,  234,  233,  317,  232,
      317,  230,  229,  228,  227,  226,  225,  223,  222,  221,
      220,  206,  317,  205,  317,  319,  319,  200,  196,  319,
      319,  319,  319,  322,  322,  322,  322,  195,  194,  193,
      319,  190,  319,  189,  322,  188,  322,  187,  347,  347,

      347,  347,  186,  185,  319,  184,  319,  183,  322,  347,
      322,  347,  182,  350,  350,  350,  350,  352,  352,  352,
      352,  181,  180,  347,  350,  347,  350,  179,  352,  178,
      352,  177,  366,  366,  366,  366,  176,  175,  350,  173,
      350,  172,  352,  366,  352,  366,  171,  170,  168,  166,
      165,  164,  163,  162,  161,  160,  159,  366,  157,  366,
      381,  381,  381,  381,  381,  381,  382,  156,  382,  382,
      382,  382,  383,  383,  383,  384,  384,  384,  385,  385,
      385,  385,  385,  385,  386,  386,  386,  386,  386,  386,
      387,  387,  387,  387,  387,  387,  388,  388,  389,  389,

      389,  389,  389,  389,  390,  390,  390,  390,  390,  390,
      392,  392,  392,  392,  392,  392,  393,  393,  393,  393,
      393,  393,  394,  394,  394,  394,  394,  394,  395,  155,
      395,  396,  396,  396,  396,  396,  396,  154,  153,  152,
      151,  150,  149,  148,  133,  130,  128,  125,  120,  119,
      117,  114,  113,  112,  110,  109,  108,  106,  105,  104,
      103,  102,  100,   98,   97,   96,   95,   94,   93,   92,
       91,   90,   89,   88,   87,   86,   84,   83,   82,   81,
       80,   75,   70,   62,   61,   59,   51,   49,   48,   43,
       42,   38,   35,   33,   22,   20,   12,   10,    8,    7,

        3,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[46] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 
    1, 0, 0, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "java_lexical_analyser.l"
#line 3 "java_lexical_analyser.l"
#include<iostream>
#include <fstream>
#include <map>
#include <vector>
using namespace std;

#define KEYWORD 1
#define IDENTIFIER 2
#define OPERATOR 3
#define SEPARATOR 4
#define INT_LITERAL 5
#define FLOAT_LITERAL 6
#define BOOL_LITERAL 7
#define CHAR_LITERAL 8
#define STRING_LITERAL 9
#define TEXT_BLOCK 10
#define NULL_LITERAL 11
#define ERROR 12
#line 894 "lex.yy.c"
#line 895 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 23 "java_lexical_analyser.l"

#line 1120 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 381 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 902 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 24 "java_lexical_analyser.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "java_lexical_analyser.l"
return var;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "java_lexical_analyser.l"
return IF;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "java_lexical_analyser.l"
return ELSE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "java_lexical_analyser.l"
return ASSERT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "java_lexical_analyser.l"
return SWITCH;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "java_lexical_analyser.l"
return CATCH;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "java_lexical_analyser.l"
return THROW;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 32 "java_lexical_analyser.l"
return TRY;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "java_lexical_analyser.l"
return arrow;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "java_lexical_analyser.l"
return CASE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 35 "java_lexical_analyser.l"
return DEFAULT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 36 "java_lexical_analyser.l"
return WHILE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "java_lexical_analyser.l"
return DO;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 38 "java_lexical_analyser.l"
return FOR;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 39 "java_lexical_analyser.l"
return BREAK;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 40 "java_lexical_analyser.l"
return YIELD;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 41 "java_lexical_analyser.l"
return CONTINUE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 42 "java_lexical_analyser.l"
return RETURN;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 43 "java_lexical_analyser.l"
return synchronized;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 44 "java_lexical_analyser.l"
return finally;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 45 "java_lexical_analyser.l"
return KEYWORD;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 46 "java_lexical_analyser.l"
return NULL_LITERAL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 47 "java_lexical_analyser.l"
return BOOL_LITERAL;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 48 "java_lexical_analyser.l"
return INT_LITERAL;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 49 "java_lexical_analyser.l"
return INT_LITERAL;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 50 "java_lexical_analyser.l"
return INT_LITERAL;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "java_lexical_analyser.l"
return INT_LITERAL;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 52 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 58 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 "java_lexical_analyser.l"
return FLOAT_LITERAL;
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 61 "java_lexical_analyser.l"
return CHAR_LITERAL;
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 62 "java_lexical_analyser.l"
return STRING_LITERAL;
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 63 "java_lexical_analyser.l"
return TEXT_BLOCK;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "java_lexical_analyser.l"
return OPERATOR;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "java_lexical_analyser.l"
return IDENTIFIER;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "java_lexical_analyser.l"
return SEPARATOR;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "java_lexical_analyser.l"
return ERROR;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "java_lexical_analyser.l"
ECHO;
	YY_BREAK
#line 1440 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 381 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 381 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 380);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 68 "java_lexical_analyser.l"


int yywrap(void){
    return 1;
}
