
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[469] =
    {   0,
       94,   92,   93,    1,   92,   93,    1,   93,    1,   92,
       93,   67,   92,   93,   92,   93,   69,   92,   93,   70,
       92,   93,   92,   93,   61,   92,   93,   62,   92,   93,
       55,   92,   93,   64,   92,   93,   58,   92,   93,   65,
       92,   93,   54,   92,   93,   68,   92,   93,   75,   92,
       93,   75,   92,   93,   63,   92,   93,   53,   92,   93,
       52,   92,   93,   74,   92,   93,   52,   92,   93,   73,
       92,   93,   91,   92,   93,   56,   92,   93,   57,   92,
       93,   71,   92,   93,   91,   92,   93,   91,   92,   93,
       91,   92,   93,   91,   92,   93,   91,   92,   93,   91,

       92,   93,   91,   92,   93,   91,   92,   93,   91,   92,
       93,   91,   92,   93,   91,   92,   93,   91,   92,   93,
       91,   92,   93,   91,   92,   93,   91,   92,   93,   91,
       92,   93,   59,   92,   93,   72,   92,   93,   60,   92,
       93,   66,   92,   93,    1,   50,   89,   44,   47,   45,
       46,   75,   75,   80,16469,   77,   82,   75,   75,   81,
       75,   51,   52,   49,   51,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   26,   91,   91,   91,
       91,   91,   91,   91,   25,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,

       91,   91,   91,   91,   48,   89,   88,   88,   80,   80,
     8277, 8277,   79, 8277,   83, 8277,   84, 8277,   77,   78,
       76,   81,   81,   81,   82,   51,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   23,   91,   91,   91,    2,   91,   91,   91,   24,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   35,   91,   91,   91,   91,
       80,   80,   79,   79,   79,   84,   84,   83,   84,   78,
       76,   81,   91,   91,   91,   30,   91,   91,    2,   91,
       91,   91,   91,   91,   29,   91,   91,   91,   91,   91,

       91,   91,   91,   91,   91,   42,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   18,   91,   91,   91,
       43,   91,   20,   91,   91,   91,   80,   79,   79,   84,
       87,   86,   91,   91,   27,   91,   34,   91,   15,   91,
       91,   91,   91,   91,   13,   91,    3,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,    6,
       91,   91,   91,   28,   91,   91,   91,   39,   91,   79,
       87,   87,   87,   86,   87,   86,   86,   86,   91,   91,
       91,   91,   91,   91,   91,   41,   91,   91,   91,   38,
       91,   91,   91,   91,    8,   91,   32,   91,   12,   91,

       21,   91,   91,   17,   91,   91,   91,   90,   87,   86,
       87,   86,   87,   86,   87,   86,   91,    4,   91,   91,
       14,   91,    5,   91,   36,   91,   91,   91,   91,   40,
       91,   10,   91,   91,   91,   91,   91,   90,   86,   87,
       11,   91,   22,   91,   91,   91,   91,   91,   91,   91,
       37,   91,   91,   31,   91,    7,   91,    9,   91,   91,
       33,   91,   16,   91,   91,   91,   19,   91
    } ;

static const flex_int16_t yy_accept[383] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   17,
       20,   23,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  136,
      139,  142,  145,  146,  147,  147,  148,  148,  149,  150,
      150,  150,  151,  152,  152,  153,  154,  155,  155,  155,
      156,  157,  157,  157,  158,  158,  159,  159,  160,  161,
      162,  163,  164,  165,  166,  167,  168,  169,  170,  171,
      172,  173,  174,  175,  176,  177,  179,  180,  181,  182,

      183,  184,  185,  187,  188,  189,  190,  191,  192,  193,
      194,  195,  196,  197,  198,  199,  200,  201,  202,  203,
      204,  205,  206,  207,  207,  208,  209,  210,  211,  211,
      211,  211,  212,  213,  213,  215,  217,  219,  220,  221,
      221,  221,  221,  221,  222,  222,  223,  224,  226,  227,
      228,  229,  230,  231,  232,  233,  234,  235,  236,  237,
      238,  239,  240,  241,  242,  244,  245,  246,  248,  249,
      250,  252,  253,  254,  255,  256,  257,  258,  259,  260,
      261,  262,  263,  264,  265,  266,  268,  269,  270,  271,
      271,  271,  271,  271,  271,  271,  272,  273,  273,  273,

      274,  275,  276,  276,  277,  278,  280,  281,  281,  281,
      281,  282,  283,  284,  285,  286,  288,  289,  291,  292,
      293,  294,  295,  297,  298,  299,  300,  301,  302,  303,
      304,  305,  306,  308,  309,  310,  311,  312,  313,  314,
      315,  316,  317,  319,  320,  321,  323,  325,  326,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  328,
      328,  328,  328,  329,  330,  331,  332,  332,  333,  334,
      335,  337,  339,  341,  342,  343,  344,  345,  347,  349,
      350,  351,  352,  353,  354,  355,  356,  357,  358,  359,
      360,  362,  363,  364,  366,  367,  368,  370,  370,  370,

      370,  370,  370,  370,  371,  371,  372,  373,  374,  376,
      376,  377,  378,  379,  380,  381,  382,  383,  384,  385,
      386,  388,  389,  390,  392,  393,  394,  395,  397,  399,
      401,  403,  404,  406,  407,  408,  409,  409,  409,  410,
      410,  412,  414,  416,  417,  418,  420,  421,  423,  425,
      427,  428,  429,  430,  432,  434,  435,  436,  437,  438,
      439,  441,  443,  445,  446,  447,  448,  449,  450,  451,
      453,  454,  456,  458,  460,  461,  463,  465,  466,  467,
      469,  469
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   28,   30,   31,   32,
       33,   33,   33,   33,   33,   34,   33,   33,   33,   35,
       33,   33,   33,   33,   33,   33,   33,   36,   33,   33,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   33,   51,   52,   53,   54,
       55,   56,   33,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    5,    5,    6,    5,    1,    1,    1,    1,
        5,    4,    4,    4,    4,    4,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    6,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[398] =
    {   0,
        0,    0,  880,  881,  881,  881,  876,  853,   64,  852,
       63,  838,  881,  881,  850,   59,  881,   58,   71,   68,
       87,  135,  881,  881,   57,  849,   61,  881,    0,  881,
      881,  848,   79,  829,   39,   73,   49,   49,   85,   89,
      816,   99,   69,  824,   98,   89,  814,  819,  881,   85,
      881,  881,  881,  881,  125,  861,  863,  881,  881,  856,
      161,  881,  881,  153,    0,    0,  158,  852,  860,  203,
      175,  181,   95,  881,  223,  881,  846,    0,  239,  881,
      836,  881,  881,  122,    0,    0,  196,  802,  804,  812,
      125,  815,  814,  801,  807,  793,  794,  792,  798,  795,

      793,  790,    0,  790,  127,  784,  717,  705,  713,  720,
       94,  720,  703,  719,  704,  709,  704,  111,  165,  158,
      707,  881,  881,  258,  881,  747,  881,  259,  743,  201,
      751,  881,  881,  736,  281,  881,  301,  881,  213,  274,
      243,  317,    0,  229,  289,  285,  321,  881,  725,  690,
      696,  705,  700,  701,  687,  685,  678,  693,  690,  685,
      683,  669,  684,  683,    0,  230,  665,  676,  672,  668,
        0,  664,  663,  638,  638,  643,  633,  633,  645,  625,
      638,  619,  620,  612,  614,    0,  614,  616,  604,  351,
      355,  366,  649,  370,  359,  320,  364,  637,  621,  382,

      881,  421,  405,  360,  425,  881,  881,  429,  195,  211,
      881,  459,  579,  585,  579,    0,  576,    0,  562,  564,
      550,  552,    0,  545,  552,  545,  536,  542,  526,  539,
      522,  515,    0,  531,  527,  522,  517,  507,  507,  498,
      502,  495,    0,  481,  483,    0,    0,  480,  490,  459,
      478,  482,  529,  489,  518,  495,  499,  504,  493,  510,
      286,  510,  385,  533,  540,  571,  231,  587,  479,  476,
        0,    0,    0,  461,  457,  454,  451,  442,    0,  437,
      428,  439,  428,  418,  412,  379,  391,  387,  367,  376,
        0,  370,  359,  352,  356,  349,    0,  392,  544,  571,

      590,  609,  391,  603,  621,  422,  633,  881,  649,  625,
      426,  653,  881,  351,  337,  328,  328,  328,  317,  329,
        0,  325,  321,    0,  314,  310,  286,    0,    0,    0,
        0,  289,    0,  297,  282,  881,  623,  323,  683,  668,
      487,  687,  881,  691,  265,    0,  277,    0,    0,    0,
      264,  250,  253,    0,    0,  237,  222,  202,  194,  233,
      721,    0,    0,  169,  179,  174,  167,  161,  139,    0,
      134,    0,    0,    0,  110,    0,    0,   78,   64,    0,
      881,  768,  774,  777,  780,  786,  792,  798,  802,  806,
      812,   71,  818,  824,  830,  833,  839

    } ;

static const flex_int16_t yy_def[398] =
    {   0,
      381,    1,  381,  381,  381,  381,  381,  381,  382,  381,
      381,  383,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  384,  381,
      381,  381,  385,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  381,  381,
      381,  381,  381,  381,  382,  381,  382,  381,  381,  381,
      383,  381,  381,  381,   21,   22,  381,  386,  387,  388,
      381,  381,  381,  381,  381,  381,  389,   22,  381,  381,
      381,  381,  381,  381,  384,  384,  385,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  381,  381,  390,  381,  381,  381,  381,  386,  391,
      387,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  392,  389,  381,  381,  381,  381,  381,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  390,
      393,  393,  390,  394,  381,  381,  381,  395,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  392,  396,
      381,  381,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  393,
      393,  393,  393,  397,  390,  390,  394,  394,  381,  395,
      391,  381,  381,  381,  381,  381,  396,  381,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  393,  393,  397,

      397,  393,  394,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  381,  393,  397,  381,  381,
      381,  381,  381,  381,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  393,
      381,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
        0,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381

    } ;

static const flex_int16_t yy_nxt[951] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   30,    4,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   29,   29,   40,
       29,   41,   29,   42,   29,   43,   44,   45,   46,   29,
       47,   48,   29,   29,   29,   49,   50,   51,   52,   56,
       59,   62,   63,   64,  209,   65,   66,   66,   66,   68,
       81,   82,   58,   58,   69,   82,   84,   58,   67,   67,
       67,   67,   58,   89,   95,   90,   85,   85,   85,   85,

       97,   57,   70,   96,   71,   71,   71,   72,  380,   58,
      110,   98,  139,  139,   91,   73,   74,   75,   74,   87,
       76,   92,   77,  379,   93,  111,   99,   94,  112,   73,
      123,   74,   75,   74,  100,  103,  101,  118,   76,  102,
      107,  104,  105,  174,  108,  119,   58,  149,  175,   77,
       70,  122,   78,   78,   78,   78,  114,  115,  109,  116,
      182,  117,   57,  381,   74,   79,   74,  183,   80,  126,
       67,   67,   67,   67,  378,   67,   67,   67,   67,   74,
       79,   74,  153,  154,  167,  168,   80,  127,  128,  127,
       70,  377,   71,   71,   71,   72,   70,  376,   72,   72,

       72,   72,  127,  128,  127,  133,  184,  187,  138,  188,
      375,  374,  130,   85,   85,   85,   85,   53,  134,  373,
      135,  135,  135,  135,  185,  372,  138,  371,  186,  266,
      139,  139,  136,  137,  136,  140,   87,  140,  336,  370,
      141,  142,  142,  142,  210,  268,  207,  136,  137,  136,
      266,  145,   74,  145,   74,  369,  146,  147,  147,  147,
      191,  192,  211,  193,  207,  309,  268,   74,  148,   74,
      148,  195,   74,  195,   74,  368,  196,  197,  197,  197,
      211,  228,  367,  148,  229,  148,  309,   74,  127,   74,
      127,  141,  142,  142,  142,  194,  366,  261,  200,  200,

      200,  200,   53,  127,  365,  127,  146,  147,  147,  147,
      201,  202,  201,  203,  148,  203,  148,  364,  204,  205,
      205,  205,  363,  362,  192,  201,  202,  201,  360,  148,
      206,  148,  206,  359,  208,  208,  208,  208,  212,  212,
      212,  212,  358,  357,  356,  206,   74,  206,   74,  127,
      148,  127,  148,  191,  192,  355,  193,  251,  252,  354,
      253,   74,  353,   74,  127,  148,  127,  148,  251,  252,
      352,  253,  191,  191,  351,  257,  196,  197,  197,  197,
      350,  259,  259,  259,  259,  349,  348,  347,  194,  206,
      346,  206,  254,  127,  345,  127,  255,  336,  335,  200,

      200,  200,  200,  254,  206,  334,  206,  258,  127,  333,
      127,  201,  202,  201,  201,  332,  201,  192,  331,  330,
      329,  252,  204,  205,  205,  205,  201,  202,  201,  201,
      328,  201,  252,  262,  327,  262,  191,  326,  263,  264,
      264,  264,  265,  265,  265,  265,  208,  208,  208,  208,
      201,  308,  201,  308,  206,  313,  206,  313,   74,  325,
       74,  251,  252,  324,  253,  201,  308,  201,  308,  206,
      313,  206,  313,   74,  323,   74,  212,  212,  212,  212,
      251,  252,  322,  253,  251,  252,  321,  253,  148,  320,
      148,  251,  251,  319,  300,  318,  254,  191,  192,  279,

      193,  302,  191,  148,  303,  148,  191,  191,  317,  257,
      259,  259,  259,  259,  316,  254,  343,  315,  343,  254,
      314,  261,  127,  381,  127,  252,  301,  263,  264,  264,
      264,  343,  194,  343,  298,  297,  258,  127,  296,  127,
      295,  258,  294,  293,  252,  292,  251,  252,  252,  253,
      304,  304,  304,  304,  291,  251,  290,  265,  265,  265,
      265,  192,  201,  289,  201,  191,  288,  287,  286,  206,
      191,  206,  285,  337,  251,  284,  338,  201,  283,  201,
      282,  254,  281,  305,  206,  305,  206,  280,  306,  307,
      307,  307,  251,  251,  279,  300,  278,  246,  277,  310,

      308,  310,  308,  276,  311,  312,  312,  312,  301,  275,
      252,  251,  252,  274,  253,  308,  313,  308,  313,  273,
      304,  304,  304,  304,  272,  251,  252,  301,  253,  271,
      270,  313,  201,  313,  201,  269,  132,  251,  306,  307,
      307,  307,  311,  312,  312,  312,  254,  201,  261,  201,
      339,  339,  339,  339,  255,  249,  251,  248,  247,  246,
      254,  340,  308,  340,  308,  245,  341,  342,  342,  342,
      344,  344,  344,  344,  244,  252,  243,  308,  343,  308,
      343,  242,  313,  241,  313,  341,  342,  342,  342,  252,
      240,  239,  238,  343,  237,  343,  236,  313,  235,  313,

      339,  339,  339,  339,  361,  361,  361,  361,  344,  344,
      344,  344,  308,  234,  308,  233,  343,  232,  343,  218,
      313,  231,  313,  230,  227,  226,  225,  308,  224,  308,
      223,  343,  222,  343,  221,  313,  220,  313,  361,  361,
      361,  361,  219,  218,  217,  216,  215,  214,  213,   58,
      343,  199,  343,   53,  130,  125,  189,  181,  180,  179,
      178,  177,  176,  173,  172,  343,  171,  343,   55,   55,
       55,   55,   55,   55,   60,  170,   60,   60,   60,   60,
       85,   85,   85,   86,   86,   86,  129,  129,  129,  129,
      129,  129,  131,  131,  131,  131,  131,  131,  132,  132,

      132,  132,  132,  132,  144,  144,  190,  190,  190,  190,
      190,  190,  198,  198,  198,  198,  198,  198,  250,  250,
      250,  250,  250,  250,  256,  256,  256,  256,  256,  256,
      260,  260,  260,  260,  260,  260,  267,  169,  267,  299,
      299,  299,  299,  299,  299,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  152,  151,  150,
       58,  143,   53,  130,  125,  381,  124,  121,  120,  113,
      106,   88,   58,   83,   58,   61,   58,   54,   53,  381,
        3,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_chk[951] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
       11,   16,   18,   18,  392,   18,   18,   18,   18,   20,
       25,   25,   18,   16,   20,   27,   27,   11,   19,   19,
       19,   19,   20,   35,   37,   35,   33,   33,   33,   33,

       38,    9,   21,   37,   21,   21,   21,   21,  379,   50,
       43,   38,   73,   73,   36,   21,   21,   21,   21,   33,
       21,   36,   21,  378,   36,   43,   39,   36,   43,   21,
       55,   21,   21,   21,   39,   40,   39,   46,   21,   39,
       42,   40,   40,  111,   42,   46,   84,   84,  111,   21,
       22,   50,   22,   22,   22,   22,   45,   45,   42,   45,
      118,   45,   55,   61,   22,   22,   22,  118,   22,   61,
       64,   64,   64,   64,  375,   67,   67,   67,   67,   22,
       22,   22,   91,   91,  105,  105,   22,   67,   67,   67,
       71,  371,   71,   71,   71,   71,   72,  369,   72,   72,

       72,   72,   67,   67,   67,   70,  119,  120,   71,  120,
      368,  367,  130,   87,   87,   87,   87,  130,   70,  366,
       70,   70,   70,   70,  119,  365,   71,  364,  119,  209,
      139,  139,   70,   70,   70,   75,   87,   75,  360,  359,
       75,   75,   75,   75,  144,  210,  139,   70,   70,   70,
      209,   79,   75,   79,   75,  358,   79,   79,   79,   79,
      124,  124,  144,  124,  139,  267,  210,   75,   79,   75,
       79,  128,  141,  128,  141,  357,  128,  128,  128,  128,
      144,  166,  356,   79,  166,   79,  267,  141,  128,  141,
      128,  140,  140,  140,  140,  124,  353,  261,  135,  135,

      135,  135,  261,  128,  352,  128,  145,  145,  145,  145,
      135,  135,  135,  137,  146,  137,  146,  351,  137,  137,
      137,  137,  347,  345,  124,  135,  135,  135,  338,  146,
      137,  146,  137,  335,  142,  142,  142,  142,  147,  147,
      147,  147,  334,  332,  327,  137,  142,  137,  142,  196,
      147,  196,  147,  190,  190,  326,  190,  191,  191,  325,
      191,  142,  323,  142,  196,  147,  196,  147,  192,  192,
      322,  192,  194,  194,  320,  194,  195,  195,  195,  195,
      319,  197,  197,  197,  197,  318,  317,  316,  190,  204,
      315,  204,  191,  197,  314,  197,  303,  298,  296,  200,

      200,  200,  200,  192,  204,  295,  204,  194,  197,  294,
      197,  200,  200,  200,  263,  293,  263,  190,  292,  290,
      289,  191,  203,  203,  203,  203,  200,  200,  200,  263,
      288,  263,  192,  202,  287,  202,  194,  286,  202,  202,
      202,  202,  205,  205,  205,  205,  208,  208,  208,  208,
      202,  306,  202,  306,  205,  311,  205,  311,  208,  285,
      208,  250,  250,  284,  250,  202,  306,  202,  306,  205,
      311,  205,  311,  208,  283,  208,  212,  212,  212,  212,
      251,  251,  282,  251,  252,  252,  281,  252,  212,  280,
      212,  254,  254,  278,  254,  277,  250,  256,  256,  276,

      256,  257,  257,  212,  257,  212,  258,  258,  275,  258,
      259,  259,  259,  259,  274,  251,  341,  270,  341,  252,
      269,  260,  259,  255,  259,  250,  254,  262,  262,  262,
      262,  341,  256,  341,  253,  249,  257,  259,  248,  259,
      245,  258,  244,  242,  251,  241,  299,  299,  252,  299,
      264,  264,  264,  264,  240,  254,  239,  265,  265,  265,
      265,  256,  264,  238,  264,  257,  237,  236,  235,  265,
      258,  265,  234,  300,  300,  232,  300,  264,  231,  264,
      230,  299,  229,  266,  265,  266,  265,  228,  266,  266,
      266,  266,  301,  301,  227,  301,  226,  225,  224,  268,

      266,  268,  266,  222,  268,  268,  268,  268,  300,  221,
      299,  302,  302,  220,  302,  266,  268,  266,  268,  219,
      304,  304,  304,  304,  217,  337,  337,  301,  337,  215,
      214,  268,  304,  268,  304,  213,  199,  300,  305,  305,
      305,  305,  310,  310,  310,  310,  302,  304,  198,  304,
      307,  307,  307,  307,  193,  189,  301,  188,  187,  185,
      337,  309,  307,  309,  307,  184,  309,  309,  309,  309,
      312,  312,  312,  312,  183,  302,  182,  307,  309,  307,
      309,  181,  312,  180,  312,  340,  340,  340,  340,  337,
      179,  178,  177,  309,  176,  309,  175,  312,  174,  312,

      339,  339,  339,  339,  342,  342,  342,  342,  344,  344,
      344,  344,  339,  173,  339,  172,  342,  170,  342,  169,
      344,  168,  344,  167,  164,  163,  162,  339,  161,  339,
      160,  342,  159,  342,  158,  344,  157,  344,  361,  361,
      361,  361,  156,  155,  154,  153,  152,  151,  150,  149,
      361,  134,  361,  131,  129,  126,  121,  117,  116,  115,
      114,  113,  112,  110,  109,  361,  108,  361,  382,  382,
      382,  382,  382,  382,  383,  107,  383,  383,  383,  383,
      384,  384,  384,  385,  385,  385,  386,  386,  386,  386,
      386,  386,  387,  387,  387,  387,  387,  387,  388,  388,

      388,  388,  388,  388,  389,  389,  390,  390,  390,  390,
      390,  390,  391,  391,  391,  391,  391,  391,  393,  393,
      393,  393,  393,  393,  394,  394,  394,  394,  394,  394,
      395,  395,  395,  395,  395,  395,  396,  106,  396,  397,
      397,  397,  397,  397,  397,  104,  102,  101,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   90,   89,   88,
       81,   77,   69,   68,   60,   57,   56,   48,   47,   44,
       41,   34,   32,   26,   15,   12,   10,    8,    7,    3,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[94] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "java_lexical_analyser.l"
#line 3 "java_lexical_analyser.l"
#include<iostream>
#include <fstream>
#include <map>
#include <vector>
using namespace std;

#include "java_parser.tab.h"

#line 884 "lex.yy.c"
#line 885 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 13 "java_lexical_analyser.l"

#line 1110 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 881 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 14 "java_lexical_analyser.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return INTEGRALTYPE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 16 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOATINGPOINTTYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 17 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return BOOLEAN;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return EXTENDS;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return SUPER;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 20 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return INTERFACE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 21 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return PUBLIC;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 22 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return PROTECTED;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 23 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return PRIVATE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return ABSTRACT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return STATIC;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FINAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return DEFAULT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return CLASS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return IMPLEMENTS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return THROWS;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return THIS;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return SYNCHRONIZED;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return VOID;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return SWITCH;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return CONTINUE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return NEW;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return IF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return DO;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return BREAK;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return THROW;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 42 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return ELSE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return CASE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 44 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return INSTANCEOF;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return RETURN;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return TRANSIENT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return CATCH;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return TRY;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FINALLY;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return VOLATILE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return NATIVE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return WHILE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return PACKAGE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return IMPORT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 55 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return NULL_LITERAL;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 56 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return BOOL_LITERAL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 57 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return ASSIGNMENT_OPERATOR;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 58 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return INC;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 59 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return DEC;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 60 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return RELAND;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 61 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return RELOR;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 62 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return RELEQ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 63 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return RELNOTEQ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 64 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return SHIFT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 65 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return RELGL;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 66 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return SEMICOLON;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 67 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return DOT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 68 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return STAR;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 69 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return OSB;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 70 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return CSB;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 71 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return COMMA;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 72 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return OCB;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 73 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return CCB;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 74 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return ONB;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 75 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return CNB;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 76 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return COLON;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 77 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return PLUS;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 78 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return MINUS;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 79 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return NEG;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 80 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return NOT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 81 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return DIV;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 82 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return MOD;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 83 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return AND;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 84 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return UP;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 85 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return OR;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 86 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return QM;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 87 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return EQ;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 88 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return INT_LITERAL;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 89 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return INT_LITERAL;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 90 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return INT_LITERAL;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 91 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return INT_LITERAL;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 92 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 93 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 94 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 95 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 96 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 97 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 98 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 99 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 100 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return FLOAT_LITERAL;}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 101 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return CHAR_LITERAL;}
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 102 "java_lexical_analyser.l"
{
                        yytext[strlen(yytext)-1] = '\0';
                        yylval.str = strdup(yytext+1);
                        return STRING_LITERAL;
                    }
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 107 "java_lexical_analyser.l"
{
                        yytext[strlen(yytext)-1] = '\0';
                        yytext[strlen(yytext)-2] = '\0';
                        yytext[strlen(yytext)-3] = '\0';
                        yylval.str = strdup(yytext+3);
                        return TEXT_BLOCK;
                    }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 114 "java_lexical_analyser.l"
{yylval.str = strdup(yytext);return IDENTIFIER;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 115 "java_lexical_analyser.l"
;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 116 "java_lexical_analyser.l"
ECHO;
	YY_BREAK
#line 1680 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 381);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 116 "java_lexical_analyser.l"


int yywrap(void){
    return 1;
}
